### ISSUE TITLE
Only activate for HDR-enabled games in Playnite

### ISSUE THREAD

**Issue by kristofferR** [Nonary/AutoHDRSwitch#1]
I attempted using this, but it didn't work like I expected it to work.

Even when HDR is disabled for the game in question in Playnite it will launch games without HDR/autoHDR in a HDR container, solely because HDR is enabled in the Moonlight client, resulting in a washed out picture.

It would be much better if this project followed Playnite HDR settings, and only activated HDR for games enabled for HDR:
https://github.com/JosefNemec/Playnite/pull/3290
https://github.com/JosefNemec/Playnite/issues/3248#issuecomment-1415333896

That way games SDR games will be displayed in SDR while HDR games will be displayed in HDR.

**Comment by Nonary** [comment]
This is not related to the primary purpose of this script, which is to sync HDR with the moonlight client.

If you want playnite to enable or disable HDR, you can utilize the actions functionality and import the HDR-FUnctions file and call the following methods

```
[HDRController]::EnableGlobalHDRState()
[HDRController]::DisableGlobalHDRState()
```
