### ISSUE TITLE
Install/Uninstall scripts assume Sunshine is installed in the default location (C:\Program Files)

### ISSUE THREAD

**Issue by arvindhmani** [Nonary/AutoHDRSwitch#2]
Installation and uninstallation will fail when the Sunshine app is installed anywhere except the default location, because of the hard-coded path to the conf file in the .ps1 script. 

A potential fix could be to first find the location of the installed service by using this Powershell cmdlet: 
Get-Service "Sunshine Service" | Select-Object BinaryPathName

Store the output in a variable, then use this path to find the sunshine.conf location.

**Comment by Andrige3** [comment]
I have the same issue! I like the solution implemented in the resolutionswapper script where you can specify the location of the .conf file.

**Comment by gutenhuu** [comment]
same here (and thanks for all the amazing automation processes for Sunshine)

**Comment by Nonary** [comment]
fixed #6
