### ISSUE TITLE
can not start service 

### ISSUE THREAD

**Issue by seanpatrick1976** [Nonary/AutoHDRSwitch#4]
When trying to install, I get the error 'can not be started due to the following error: Cannot start serice SunshineService on computer '.'.

I've set sunshine to debug, in addition to adjusting the terminal settings in developer options. Sunshine is in its default location. Any ideas?

**Comment by Nonary** [comment]
Make sure sunshine is on latest version, also make sure you don't have any strange setups like trying to run it with the built in administrator account and or completely disabling UAC as both of those actions will break the installation script.

**Comment by Nonary** [comment]
Closing out, no response.
